{application,gen_batch_server,
             [{description,"Generic batching server"},
              {licenses,["ASL2","MPL2"]},
              {links,[{"github",
                       "https://github.com/rabbitmq/gen-batch-server"}]},
              {vsn,"0.8.6"},
              {modules, ['gen_batch_server']},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]}]}.
