version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
      day: monday
      time: "03:10"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /dc3-web
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:20"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directories:
      - /
      - /dc3-web
      - /dc3/dependencies/rabbitmq
      - /dc3/dependencies/postgres
    schedule:
      interval: weekly
      day: monday
      time: "03:40"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
