/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    403: typeof import('./src/components/error/403.vue')['default']
    404: typeof import('./src/components/error/404.vue')['default']
    500: typeof import('./src/components/error/500.vue')['default']
    BaseCard: typeof import('./src/components/card/base/BaseCard.vue')['default']
    BlankCard: typeof import('./src/components/card/blank/BlankCard.vue')['default']
    DetailCard: typeof import('./src/components/card/detail/DetailCard.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Particles: typeof import('./src/components/particles/particles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCard: typeof import('./src/components/card/skeleton/SkeletonCard.vue')['default']
    TitleCard: typeof import('./src/components/card/title/TitleCard.vue')['default']
  }
}
