allowBuilds:
  '@parcel/watcher': true
minimumReleaseAgeExclude:
  - '@intlify/core-base@11.4.4'
  - '@intlify/devtools-types@11.4.4'
  - '@intlify/message-compiler@11.4.4'
  - '@intlify/shared@11.4.4'
  - '@types/node@25.9.0'
  - '@vue/language-core@3.3.0'
  - vue-i18n@11.4.4
  - vue-tsc@3.3.0
