-- Copyright 2016-present the IoT DC3 original author or authors.
--
-- Identity column for dc3_attachment.id.
--
-- WHY: initdb seeds only run on FIRST container start (Docker entrypoint
-- /docker-entrypoint-initdb.d). dc3_attachment.id was declared as a plain
-- BIGINT PRIMARY KEY without GENERATED BY DEFAULT AS IDENTITY (unlike
-- dc3_session/dc3_message), while R2dbcAttachmentStore.save() inserts without
-- an explicit id — every upload violated NOT NULL and failed with
-- "Attachment file save failed" (HTTP 500). The canonical DDL now carries the
-- identity clause; this migration converges databases initialized before the
-- fix.
--
-- IDEMPOTENT: safe to re-run — the DO block checks pg_attribute.attidentity
-- before altering, and the fingerprint UPDATE is guarded by the old hash.
--
-- Run against an already-initialized database:
--   docker exec -i <postgres-container> psql -U dc3 -d dc3 \
--     -v ON_ERROR_STOP=1 < 04-attachment-id-identity.sql
--
-- Verify afterwards:
--   SELECT fingerprint_version, ddl_hash FROM public.dc3_schema_fingerprint;
--   -- expect: 2 | 0d9ad80328ef1a6ba91e53cf0c6db25812b8bd236e280939f967beee687d5108
--   SELECT a.attidentity FROM pg_attribute a
--     JOIN pg_class c ON c.oid = a.attrelid
--     WHERE c.relname = 'dc3_attachment' AND a.attname = 'id';  -- expect: d

BEGIN;

SET search_path TO dc3_agentic;

-- ----------------------------
-- dc3_attachment: id becomes an identity column
-- ----------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        WHERE c.relname = 'dc3_attachment'
          AND a.attname = 'id'
          AND a.attidentity = ''
    ) THEN
        ALTER TABLE dc3_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        -- Rows inserted before the fix carried explicit ids; start the
        -- generated sequence past any survivor so inserts never collide.
        EXECUTE format(
            'SELECT setval(pg_get_serial_sequence(''dc3_attachment'', ''id''), GREATEST(COALESCE((SELECT MAX(id) FROM dc3_attachment), 0) + 1, 1), false)'
        );
    END IF;
END
$$;

-- ----------------------------
-- Schema fingerprint resync (databases initialized before this change)
-- ----------------------------
UPDATE public.dc3_schema_fingerprint
SET ddl_hash      = '0d9ad80328ef1a6ba91e53cf0c6db25812b8bd236e280939f967beee687d5108',
    generated_at  = CURRENT_TIMESTAMP
WHERE fingerprint_version = 2
  AND ddl_hash = 'c8ff34a0c7534ae479137f4ff95b1c41caa8b666b448870de419933d679fbb85';

COMMIT;
