#
# Copyright 2016-present the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### --------------------- Point ---------------------
### 新增 Point
POST http://{{dc3-manager}}/manager/point/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "测试位号",
  "type": "string",
  "rw": 0,
  "base": 0,
  "minimum": -999999,
  "maximum": 999999,
  "multiple": 1,
  "format": "%.3f",
  "unit": "mm",
  "profileId": -1,
  "description": "测试位号"
}


### 修改 Point
POST http://{{dc3-manager}}/manager/point/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "name": "测试位号",
  "type": "string",
  "rw": 0,
  "base": 0,
  "minimum": -999999,
  "maximum": 999999,
  "multiple": 1,
  "format": "%.3f",
  "unit": "mm",
  "profileId": -1,
  "description": "测试位号"
}


### 根据 ID 查询 Point
GET http://{{dc3-manager}}/manager/point/id/1
Accept: */*
Cache-Control: no-cache



### 分页查询 Point
POST http://{{dc3-manager}}/manager/point/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "",
  "page": {
    "current": 1,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 根据 ID 删除 Point
POST http://{{dc3-manager}}/manager/point/delete/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache


### --------------------- Point Attribute ---------------------
### 新增 PointAttribute
POST http://{{dc3-manager}}/manager/point_attribute/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "displayName": "测试IP",
  "name": "ip",
  "type": "string",
  "value": "localhost",
  "driverId": -1,
  "description": "测试位号属性"
}


### 修改 PointAttribute
POST http://{{dc3-manager}}/manager/point_attribute/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "displayName": "测试IP",
  "name": "ip",
  "type": "string",
  "value": "localhost",
  "driverId": -1,
  "description": "测试位号属性"
}


### 根据 ID 查询 PointAttribute
GET http://{{dc3-manager}}/manager/point_attribute/id/1
Accept: */*
Cache-Control: no-cache



### 分页查询 PointAttribute
POST http://{{dc3-manager}}/manager/point_attribute/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "displayName": "",
  "page": {
    "current": 1,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 根据 ID 删除 PointAttribute
POST http://{{dc3-manager}}/manager/point_attribute/delete/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache


### --------------------- Point Attribute Config ---------------------
### 新增 PointInfo
POST http://{{dc3-manager}}/manager/point_attribute_config/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "pointAttributeId": 1,
  "value": "localhost",
  "deviceId": -1,
  "pointId": -1,
  "description": "测试位号配置"
}


### 修改 PointInfo
POST http://{{dc3-manager}}/manager/point_attribute_config/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "pointAttributeId": 1,
  "value": "localhost",
  "deviceId": -1,
  "pointId": -1,
  "description": "测试位号配置"
}


### 根据 ID 查询 PointInfo
GET http://{{dc3-manager}}/manager/point_attribute_config/id/1
Accept: */*
Cache-Control: no-cache



### 分页查询 PointInfo
POST http://{{dc3-manager}}/manager/point_attribute_config/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "page": {
    "current": 1,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 根据 ID 删除 PointInfo
POST http://{{dc3-manager}}/manager/point_attribute_config/delete/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache