/*
 * Copyright 2016-present the IoT DC3 original author or authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package api.common;

// Config
option java_package = "io.github.pnoker.api.common";
option java_outer_classname = "PageProto";
option objc_class_prefix = "Common";
option java_multiple_files = true;

// Canonical request used by all new list RPCs. Offset is zero based and limit
// is bounded by the server (currently 1..200). Do not add page-number fields.
message PageRequest {
  int64 offset = 1;
  int32 limit = 2;
  repeated SortSpec sort = 3;
}

message SortSpec {
  string field = 1;
  SortDirection direction = 2;
}

enum SortDirection {
  SORT_DIRECTION_UNSPECIFIED = 0;
  SORT_DIRECTION_ASC = 1;
  SORT_DIRECTION_DESC = 2;
}

message OffsetPage {
  int64 offset = 1;
  int32 limit = 2;
  int64 total = 3;
  bool has_next = 4;
}

message CursorPage {
  string next_cursor = 1;
  bool has_next = 2;
}
