#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dc3-gateway
  namespace: dc3
  labels:
    app.kubernetes.io/part-of: iot-dc3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dc3-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dc3-web
  namespace: dc3
  labels:
    app.kubernetes.io/part-of: iot-dc3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dc3-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
