apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dc3-gateway
  namespace: dc3
  labels:
    app.kubernetes.io/part-of: iot-dc3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dc3-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dc3-web
  namespace: dc3
  labels:
    app.kubernetes.io/part-of: iot-dc3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dc3-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
