apiVersion: v1
kind: Service
metadata:
  name: dc3-gateway
  namespace: dc3
  labels:
    app.kubernetes.io/name: dc3-gateway
    app.kubernetes.io/part-of: iot-dc3
spec:
  type: ClusterIP
  selector:
    app: dc3-gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
