server:
  port: ${DC3_AGENTIC_PORT:8600}

spring:
  application:
    name: @project.artifactId@
  webflux:
    base-path: /agentic
  profiles:
    active:
      - ${NODE_ENV:dev}

dc3:
  facade:
    mode: ${DC3_FACADE_MODE:grpc}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  file:
    name: dc3/logs/center/agentic/${spring.application.name}.log
