server:
  port: ${DC3_AGENTIC_PORT:8600}

spring:
  application:
    name: @project.artifactId@
  webflux:
    base-path: /agentic
  profiles:
    active:
      - ${NODE_ENV:dev}

dc3:
  facade:
    mode: ${DC3_FACADE_MODE:grpc}

logging:
  file:
    name: dc3/logs/center/agentic/${spring.application.name}.log
