package io.github.pnoker.center.manager.manager.impl;

import io.github.pnoker.center.manager.entity.model.GroupDO;
import io.github.pnoker.center.manager.mapper.GroupMapper;
import io.github.pnoker.center.manager.manager.GroupManager;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * <p>
 * 分组表 服务实现类
 * </p>
 *
 * @author Automatic Generated By Mybatis Plus
 * @since 2023-11-02
 */
@Service
public class GroupManagerImpl extends ServiceImpl<GroupMapper, GroupDO> implements GroupManager {

}
