package io.github.pnoker.center.manager.manager.impl;

import io.github.pnoker.center.manager.entity.model.LabelBindDO;
import io.github.pnoker.center.manager.mapper.LabelBindMapper;
import io.github.pnoker.center.manager.manager.LabelBindManager;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * <p>
 * 标签关联表 服务实现类
 * </p>
 *
 * @author Automatic Generated By Mybatis Plus
 * @since 2023-11-02
 */
@Service
public class LabelBindManagerImpl extends ServiceImpl<LabelBindMapper, LabelBindDO> implements LabelBindManager {

}
