{ { - range $name, $svc := .Values.services } }
  { { - if $svc.enabled } }
---
apiVersion: v1
kind: Service
metadata:
  name: dc3-{{ $name }}
  labels:
    { { - include "dc3.labels" $ | nindent 4 } }
spec:
  type: ClusterIP
  selector:
    app: dc3-{{ $name }}
  ports:
    - name: http
      port: { { $svc.httpPort } }
      targetPort: http
  { { - if $svc.grpcPort } }
- name: grpc
  port: { { $svc.grpcPort } }
  targetPort: grpc
  { { - end } }
  { { - if $svc.httpsPort } }
- name: https
  port: { { $svc.httpsPort } }
  targetPort: https
  { { - end } }
  { { - end } }
  { { - end } }
