apiVersion: v1
kind: ConfigMap
metadata:
  name: dc3-config
  labels:
    {{- include "dc3.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
