{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dc3-ingress
  labels:
    {{- include "dc3.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if and .Values.ingress.tls .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: dc3-gateway
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dc3-web
                port:
                  name: http
{{- end }}
