#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

{ { - if .Values.postgres.enabled } }
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dc3-postgres
  labels:
    { { - include "dc3.labels" . | nindent 4 } }
spec:
  serviceName: dc3-postgres
  replicas: 1
  selector:
    matchLabels:
      app: dc3-postgres
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dc3-postgres
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: dc3-postgres
          image: "{{ .Values.image.registry }}/{{ .Values.postgres.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: dc3-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: { { include "dc3.secretName" . } }
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: { { include "dc3.secretName" . } }
                  key: POSTGRES_PASSWORD
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            { { - toYaml .Values.postgres.resources | nindent 12 } }
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "dc3", "-d", "dc3" ]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "dc3", "-d", "dc3" ]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        { { - with .Values.postgres.storageClass } }
        storageClassName: { { . } }
        { { - end } }
        resources:
          requests:
            storage: { { .Values.postgres.storage } }
  { { - end } }
