{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dc3-rabbitmq
  labels:
    {{- include "dc3.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: dc3-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: mqtt
      port: 1883
      targetPort: mqtt
{{- end }}
