{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dc3-rabbitmq
  labels:
    {{- include "dc3.labels" . | nindent 4 }}
spec:
  serviceName: dc3-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: dc3-rabbitmq
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dc3-rabbitmq
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: dc3-rabbitmq
          image: "{{ .Values.image.registry }}/{{ .Values.rabbitmq.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                configMapKeyRef:
                  name: dc3-config
                  key: RABBITMQ_VIRTUAL_HOST
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dc3.secretName" . }}
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "dc3.secretName" . }}
                  key: RABBITMQ_PASSWORD
          ports:
            - name: amqp
              containerPort: 5672
            - name: amqps
              containerPort: 5671
            - name: mqtt
              containerPort: 1883
            - name: management
              containerPort: 15672
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.rabbitmq.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.rabbitmq.storage }}
{{- end }}
