{ { - if not .Values.existingSecret } }
apiVersion: v1
kind: Secret
metadata:
  name: dc3-secrets
  labels:
    { { - include "dc3.labels" . | nindent 4 } }
type: Opaque
stringData:
  { { - range $k, $v := .Values.secrets } }
  { { $k } }: { { $v | quote } }
  { { - end } }
  { { - end } }
