#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Pre-release environment configuration will overwrite the content configured in application-*.yml
spring:
  cloud:
    nacos:
      server-addr: ${NACOS_HOST:dc3-register}:${NACOS_PORT:8848}
      username: dc3
      password: dc3
      discovery:
        namespace: ${NODE_ENV:pre}
    gateway.server.webflux:
      routes:
        # token
        - id: auth_route_token
          uri: lb://dc3-center-auth
          predicates:
            - Path=/api/v3/auth/token/**
          filters:
            - StripPrefix=2
        # auth
        - id: auth_route
          uri: lb://dc3-center-auth
          predicates:
            - Path=/api/v3/auth/user/**,/api/v3/auth/tenant/**,/api/v3/auth/dictionary/**
          filters:
            - StripPrefix=2
            - Authentic
        # manager
        - id: manager_route
          uri: lb://dc3-center-manager
          predicates:
            - Path=/api/v3/manager/**
          filters:
            - StripPrefix=2
            - Authentic
        # data
        - id: data_route
          uri: lb://dc3-center-data
          predicates:
            - Path=/api/v3/data/**
          filters:
            - StripPrefix=2
            - Authentic
        # ekuiper
        - id: ekuiper_route
          uri: lb://dc3-center-ekuiper:8600
          predicates:
            - Path=/api/v3/ekuiper/**
          filters:
            - StripPrefix=2
            - Authentic

grpc:
  client:
    dc3-center-auth:
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext