#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

services:
  elasticsearch:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-elasticsearch:2025.2
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    container_name: dc3-elasticsearch
    hostname: dc3-elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "20"
    networks:
      dc3net:
        aliases:
          - dc3-elasticsearch

  logstash:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-logstash:2025.2
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    container_name: dc3-logstash
    hostname: dc3-logstash
    volumes:
      - logs:/usr/share/logstash/dc3/logs
      - logstash:/usr/share/logstash/data
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "20"
    networks:
      dc3net:
        aliases:
          - dc3-logstash

  apm:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-apm:2025.2
    restart: always
    depends_on:
      - elasticsearch
    container_name: dc3-apm
    hostname: dc3-apm
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "20"
    networks:
      dc3net:
        aliases:
          - dc3-apm

  kibana:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-kibana:2025.2
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    container_name: dc3-kibana
    hostname: dc3-kibana
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "20"
    networks:
      dc3net:
        aliases:
          - dc3-kibana

volumes:
  logs:
  elasticsearch:
  logstash:

networks:
  dc3net:
    driver: bridge
