#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  postgres:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-postgres:2025.2
    restart: always
    ports:
      - '35432:5432'
    container_name: dc3-postgres
    hostname: dc3-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: '10M'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-postgres

  rabbitmq:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-rabbitmq:2025.2
    restart: always
    ports:
      - '5671:5671'
      - '5672:5672'
      - '15672:15672'
    container_name: dc3-rabbitmq
    hostname: dc3-rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    logging:
      driver: json-file
      options:
        max-size: '10M'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-rabbitmq

  emqx:
    image: registry.cn-beijing.aliyuncs.com/dc3/dc3-emqx:2025.2
    restart: always
    ports:
      - '8083:8083'
      - '8084:8084'
      - '1883:1883'
      - '8883:8883'
      - '18083:18083'
    container_name: dc3-emqx
    hostname: dc3-emqx
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    logging:
      driver: json-file
      options:
        max-size: '10M'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-emqx

volumes:
  postgres:
  rabbitmq:
  emqx_data:
  emqx_log:


networks:
  dc3net:
    driver: bridge
...
