#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

services:
  emqx:
    image: pnoker/dc3-emqx:2025.2
    restart: always
    ports:
      - "38083:8083"
      - "38084:8084"
      - "31883:1883"
      - "38883:8883"
      - "18083:18083"
    container_name: dc3-emqx
    hostname: dc3-emqx
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "20"
    networks:
      dc3net:
        aliases:
          - dc3-emqx

volumes:
  emqx_data:
  emqx_log:

networks:
  dc3net:
    driver: bridge
