%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.6.0

-ifndef(prometheus_model).
-define(prometheus_model, true).

-define(prometheus_model_gpb_version, "4.6.0").

-ifndef('LABELPAIR_PB_H').
-define('LABELPAIR_PB_H', true).
-record('LabelPair',
        {name                   :: iodata() | undefined, % = 1
         value                  :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('GAUGE_PB_H').
-define('GAUGE_PB_H', true).
-record('Gauge',
        {value                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1
        }).
-endif.

-ifndef('COUNTER_PB_H').
-define('COUNTER_PB_H', true).
-record('Counter',
        {value                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1
        }).
-endif.

-ifndef('QUANTILE_PB_H').
-define('QUANTILE_PB_H', true).
-record('Quantile',
        {quantile               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1
         value                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
        }).
-endif.

-ifndef('SUMMARY_PB_H').
-define('SUMMARY_PB_H', true).
-record('Summary',
        {sample_count           :: non_neg_integer() | undefined, % = 1, 32 bits
         sample_sum             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
         quantile = []          :: [prometheus_model:'Quantile'()] | undefined % = 3
        }).
-endif.

-ifndef('UNTYPED_PB_H').
-define('UNTYPED_PB_H', true).
-record('Untyped',
        {value                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1
        }).
-endif.

-ifndef('HISTOGRAM_PB_H').
-define('HISTOGRAM_PB_H', true).
-record('Histogram',
        {sample_count           :: non_neg_integer() | undefined, % = 1, 32 bits
         sample_sum             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
         bucket = []            :: [prometheus_model:'Bucket'()] | undefined % = 3
        }).
-endif.

-ifndef('BUCKET_PB_H').
-define('BUCKET_PB_H', true).
-record('Bucket',
        {cumulative_count       :: non_neg_integer() | undefined, % = 1, 32 bits
         upper_bound            :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2
        }).
-endif.

-ifndef('METRIC_PB_H').
-define('METRIC_PB_H', true).
-record('Metric',
        {label = []             :: [prometheus_model:'LabelPair'()] | undefined, % = 1
         gauge                  :: prometheus_model:'Gauge'() | undefined, % = 2
         counter                :: prometheus_model:'Counter'() | undefined, % = 3
         summary                :: prometheus_model:'Summary'() | undefined, % = 4
         untyped                :: prometheus_model:'Untyped'() | undefined, % = 5
         histogram              :: prometheus_model:'Histogram'() | undefined, % = 7
         timestamp_ms           :: integer() | undefined % = 6, 32 bits
        }).
-endif.

-ifndef('METRICFAMILY_PB_H').
-define('METRICFAMILY_PB_H', true).
-record('MetricFamily',
        {name                   :: iodata() | undefined, % = 1
         help                   :: iodata() | undefined, % = 2
         type                   :: 'COUNTER' | 'GAUGE' | 'SUMMARY' | 'UNTYPED' | 'HISTOGRAM' | integer() | undefined, % = 3, enum MetricType
         metric = []            :: [prometheus_model:'Metric'()] | undefined % = 4
        }).
-endif.

-endif.
