#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

driver:
  tenant: default
  name: 联讯通Dtu驱动
  code: DtuYeeComDriver
  type: DRIVER_SERVER
  remark: @project.description@
  custom:
    tcp:
      port: ${TCP_PORT:9001}
    udp:
      port: ${UDP_PORT:9002}
  schedule:
    # 定时读数据
    read:
      enable: false
      cron: '0/30 * * * * ?'
    custom:
      enable: true
      cron: '0/5 * * * * ?'
  point-attribute:
    - display-name: 关键字
      attribute-name: key
      attribute-type-flag: STRING
      default-value: 62
      remark: 报文关键字
    - display-name: 起始字节
      attribute-name: start
      attribute-type-flag: INT
      default-value: 0
      remark: 起始字节, 包含该字节
    - display-name: 结束字节
      attribute-name: end
      attribute-type-flag: INT
      default-value: 8
      remark: 结束字节, 不包含该字节
    - display-name: 类型
      attribute-name: type
      attribute-type-flag: STRING
      default-value: string
      remark: 解析类型, short, int, long, float, double, boolean, string

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - ${NODE_ENV:dev}

logging:
  file:
    name: dc3/logs/driver/dtu-yeecom/${spring.application.name}.log