#
#  Copyright 2018-2020 Pnoker. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

### --------------------- Driver ---------------------
### 新增 Driver
#/manager/driver/add
POST http://localhost:8400/manager/driver/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "测试驱动",
  "serviceName": "dc3-driver-test",
  "host": "127.0.0.1",
  "port": 8799,
  "description": "测试驱动"
}


### 新增 Driver
#/manager/driver/batchImport
POST http://localhost:8400/manager/driver/batchImport
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

< ./file/batch-import.json


### 修改 Driver
#/manager/driver/update
POST http://localhost:8400/manager/driver/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "name": "测试驱动",
  "serviceName": "dc3-driver-test",
  "host": "127.0.0.1",
  "port": 8799,
  "description": "测试驱动"
}


### 根据 ID 查询 Driver
#/manager/driver/id/:id
GET http://localhost:8400/manager/driver/id/1
Accept: */*
Cache-Control: no-cache


### 查询 Driver 服务状态
#/manager/driver/status，支持name\serverName\host模糊查询，port精准查询
POST http://localhost:8400/manager/driver/status
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "",
  "page": {
    "current": 1,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 分页查询 Driver
#/manager/driver/list，支持name\serverName\host模糊查询，port精准查询
POST http://localhost:8400/manager/driver/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "",
  "page": {
    "current": 1,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 根据 ID 删除 Driver
#/manager/driver/delete/:id
POST http://localhost:8400/manager/driver/delete/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache


### --------------------- Driver Attribute ---------------------
### 新增 DriverAttribute
#/manager/driverAttribute/add
POST http://localhost:8400/manager/driverAttribute/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "displayName": "测试IP",
  "name": "ip",
  "type": "string",
  "value": "localhost",
  "driverId": -1,
  "description": "测试驱动属性"
}


### 修改 DriverAttribute
#/manager/driverAttribute/update
POST http://localhost:8400/manager/driverAttribute/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "displayName": "测试IP",
  "name": "ip",
  "type": "string",
  "value": "localhost",
  "driverId": -1,
  "description": "测试驱动属性"
}


### 根据 ID 查询 DriverAttribute
#/manager/driverAttribute/id/:id
GET http://localhost:8400/manager/driverAttribute/id/1
Accept: */*
Cache-Control: no-cache



### 分页查询 DriverAttribute
#/manager/driverAttribute/list，支持displayName模糊查询，name\type\driverId精准查询
POST http://localhost:8400/manager/driverAttribute/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "displayName": "",
  "page": {
    "current": 1,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 根据 ID 删除 DriverAttribute
#/manager/driverAttribute/delete/:id
POST http://localhost:8400/manager/driverAttribute/delete/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache


### --------------------- Driver Info ---------------------
### 新增 DriverInfo
#/manager/driverInfo/add
POST http://localhost:8400/manager/driverInfo/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "driverAttributeId": 1,
  "value": "localhost",
  "profileId": -1,
  "description": "测试驱动配置"
}


### 修改 DriverInfo
#/manager/driverInfo/update
POST http://localhost:8400/manager/driverInfo/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "driverAttributeId": 1,
  "value": "localhost",
  "profileId": -1,
  "description": "测试驱动配置"
}


### 根据 ID 查询 DriverInfo
#/manager/driverInfo/id/:id
GET http://localhost:8400/manager/driverInfo/id/1
Accept: */*
Cache-Control: no-cache



### 分页查询 DriverInfo
#/manager/driverInfo/list，支持driverAttributeId\profileId精准查询
POST http://localhost:8400/manager/driverInfo/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "page": {
    "current": 1,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 根据 ID 删除 DriverInfo
#/manager/driverInfo/delete/:id
POST http://localhost:8400/manager/driverInfo/delete/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###