#
#  Copyright 2018-2020 Pnoker. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

### --------------------- User ---------------------
### 新增 User
#/auth/user/add
POST http://localhost:8300/auth/user/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "dc3",
  "password": "dc3dc3dc3",
  "description": "平台开发者账号"
}


### 修改 User
#/auth/user/update
POST http://localhost:8300/auth/user/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "password": "dc3dc3dc3",
  "enable": true,
  "description": "平台开发者账号"
}


### 根据 ID 重置 User 密码
#/auth/user/restPassword/:id
POST http://localhost:8300/auth/user/rest/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache


### 根据 ID 查询 User
#/auth/user/id/:id
GET http://localhost:8300/auth/user/id/1
Accept: */*
Cache-Control: no-cache


### 根据 Name 查询 User
#/auth/user/name/:name
GET http://localhost:8300/auth/user/name/dc3
Accept: */*
Cache-Control: no-cache


### 分页查询 User
#/auth/user/list，支持name模糊查询
POST http://localhost:8300/auth/user/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "",
  "page": {
    "current": 1,
    "size": 500,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 检测用户是否存在
#/auth/user/check/:name
GET http://localhost:8300/auth/user/check/dc3
Accept: */*
Cache-Control: no-cache


### 根据 ID 删除 User
#/auth/user/delete/:id
POST http://localhost:8300/auth/user/delete/1
Accept: */*
Content-Type: application/json
Cache-Control: no-cache


### --------------------- Token ---------------------
### 生成用户 Salt
#/auth/token/salt
GET http://localhost:8300/auth/token/salt
Accept: */*
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

username=pnoker


### 生成用户 Token 令牌
#/auth/token/generate
POST http://localhost:8300/auth/token/generate
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "name": "pnoker",
  "password": "900eb6ba49ffd909b74b71da2a395824"
}


### 检测用户 Token 令牌是否有效
#/auth/token/:token
GET http://localhost:8300/auth/token/check
Accept: */*
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

username=pnoker&token=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJwbm9rZXIiLCJpYXQiOjE1OTIwNTgyMTEsImV4cCI6MTU5MjA3OTgxMX0.nJ2fmItykFVqaRIbjIeqNVc4vDAOP5lPyNZtfcfNzgg


### 注销用户 Token 令牌
#/auth/token/cancel
GET http://localhost:8300/auth/token/cancel
Accept: */*
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

username=pnoker

### --------------------- BlackIp ---------------------
### 新增 BlackIp
#/auth/blackIp/add
POST http://localhost:8300/auth/blackIp/add
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "ip": "192.168.0.1",
  "description": "测试黑名单Ip"
}


### 修改 BlackIp
#/auth/blackIp/update
POST http://localhost:8300/auth/blackIp/update
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1,
  "ip": "192.168.0.1",
  "enable": true,
  "description": "测试黑名单Ip"
}


### 根据 ID 查询 BlackIp
#/auth/blackIp/id/:id
GET http://localhost:8300/auth/blackIp/id/1
Accept: */*
Cache-Control: no-cache


### 根据 Ip 查询 BlackIp
#/auth/user/ip/:ip
GET http://localhost:8300/auth/blackIp/ip/192.168.0.1
Accept: */*
Cache-Control: no-cache


### 分页查询 BlackIp
#/auth/blackIp/list，支持ip模糊查询
POST http://localhost:8300/auth/blackIp/list
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "ip": "",
  "page": {
    "current": 1,
    "size": 500,
    "orders": [
      {
        "column": "id",
        "asc": false
      }
    ]
  }
}


### 检测BlackIp是否存在
#/auth/blackIp/check/:ip
GET http://localhost:8300/auth/blackIp/check/192.168.0.1
Accept: */*
Cache-Control: no-cache


### 根据 ID 删除 BlackIp
#/auth/blackIp/delete/:id
POST http://localhost:8300/auth/blackIp/delete/3
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###

