#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

server:
  port: ${DC3_SINGLE_PORT:8100}

spring:
  config:
    import: classpath:application-r2dbc.yml
  application:
    name: @project.artifactId@
  webflux:
    base-path: /single
  grpc:
    server:
      port: ${DC3_SINGLE_GRPC_PORT:9100}
  profiles:
    active:
      - ${NODE_ENV:dev}

dc3:
  data:
    point:
      batch:
        batch-size: ${POINT_BATCH_SIZE:500}
        receive-timeout-millis: ${POINT_BATCH_RECEIVE_TIMEOUT_MILLIS:100}
        concurrent-consumers: ${POINT_CONCURRENT_CONSUMERS:4}
        max-concurrent-consumers: ${POINT_MAX_CONCURRENT_CONSUMERS:16}
        prefetch-count: ${POINT_PREFETCH_COUNT:1000}
        max-retries: ${POINT_RETRY_MAX_RETRIES:3}
        retry-initial-interval-millis: ${POINT_RETRY_INITIAL_INTERVAL_MILLIS:1000}
        retry-multiplier: ${POINT_RETRY_MULTIPLIER:2}
        retry-max-interval-millis: ${POINT_RETRY_MAX_INTERVAL_MILLIS:10000}
  facade:
    auth:
      mode: local
    manager:
      mode: local
    data:
      mode: local

logging:
  file:
    name: dc3/logs/center/single/${spring.application.name}.log
