package io.github.pnoker.center.manager.manager;

import io.github.pnoker.center.manager.entity.model.GroupDO;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * <p>
 * 分组表 服务类
 * </p>
 *
 * @author Automatic Generated By Mybatis Plus
 * @since 2023-11-02
 */
public interface GroupManager extends IService<GroupDO> {

}
