#### 查询rtmp
GET localhost:8300/api/v3/dbs/rtmp
Content-Type: application/json
Accept: application/json

{
  "autoStart": "false",
  "name": "在线"
}

#### 根据ID查询rtmp
GET localhost:8300/api/v3/dbs/rtmp/id/31
Accept: application/json

#### 根据ID删除rtmp
DELETE localhost:8300/api/v3/dbs/rtmp/id/31
Accept: application/json

#### 修改rtmp
PUT localhost:8300/api/v3/dbs/rtmp
Content-Type: application/json
Accept: application/json

{
  "id": 31,
  "userId": -1,
  "description": "在线视频流（无限动力预告），用于测试使用",
  "createTime": "2019-09-30T16:00:00.000+0000",
  "updateTime": "2019-09-30T16:00:00.000+0000",
  "deleted": 0,
  "name": "在线测试视频test11",
  "rtspUrl": "http://vfx.mtime.cn/Video/2019/03/19/mp4/190319104618910544.mp4",
  "rtmpUrl": "rtmp://iotdc3.nginx:1935/rtmp/190314223540373995_online",
  "command": "{exe} -re -stream_loop -1 -i {rtsp_url} -vcodec copy -acodec copy -f flv -y {rtmp_url}",
  "videoType": 0,
  "autoStart": false,
  "nodeId": -1,
  "imageId": -1
}

#### 新增rtmp
POST localhost:8300/api/v3/dbs/rtmp
Content-Type: application/json
Accept: application/json

{
  "userId": -1,
  "description": "在线视频流（无限动力预告），用于测试使用",
  "createTime": "2019-09-30T16:00:00.000+0000",
  "updateTime": "2019-09-30T16:00:00.000+0000",
  "deleted": 0,
  "name": "在线测试视频test",
  "rtspUrl": "http://vfx.mtime.cn/Video/2019/03/19/mp4/190319104618910544.mp4",
  "rtmpUrl": "rtmp://iotdc3.nginx:1935/rtmp/190314223540373995_online",
  "command": "{exe} -re -stream_loop -1 -i {rtsp_url} -vcodec copy -acodec copy -f flv -y {rtmp_url}",
  "videoType": 0,
  "autoStart": false,
  "nodeId": -1,
  "imageId": -1
}

###