#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Test environment configuration will overwrite the content configured in application-*.yml
spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:postgresql://${POSTGRES_HOST:dc3-postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dc3}?currentSchema=${POSTGRES_SCHEMA:dc3_manager}&applicationName=dc3&ssl=false&stringtype=unspecified&clientEncoding=UTF8&serverTimezone=Asia/Shanghai
          username: ${POSTGRES_USERNAME:dc3}
          password: ${POSTGRES_PASSWORD:dc3dc3dc3}
  rabbitmq:
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:dc3}
    host: ${RABBITMQ_HOST:dc3-rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:dc3}
    password: ${RABBITMQ_PASSWORD:dc3dc3dc3}
  data:
    redis:
      host: ${REDIS_HOST:dc3-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:dc3dc3dc3}
  cache:
    redis:
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:15M}

grpc:
  client:
    dc3-center-auth:
      address: 'static://${CENTER_AUTH_HOST:dc3-center-auth}:9300'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    dc3-center-data:
      address: 'static://${CENTER_DATA_HOST:dc3-center-data}:9500'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

logging:
  level:
    io.github.pnoker: DEBUG