/*
 * Copyright 2016-present the IoT DC3 original author or authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package io.github.pnoker.common.agentic.entity.vo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.List;

/**
 * A single SSE chunk in the OpenAI streaming chat completion response.
 *
 * @author pnoker
 * @version 2025.9.0
 * @see <a href="https://platform.openai.com/docs/api-reference/chat/streaming">OpenAI
 * Streaming</a>
 * @since 2016.10.1
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "A single SSE chunk returned in an OpenAI-compatible streaming chat completion response.")
public class ChatCompletionChunkVO {

    @Schema(description = "Unique identifier for this streaming completion, shared across all chunks of the same response.", example = "chatcmpl-abc123")
    private String id;

    @Schema(description = "Object type for a streaming chunk; always 'chat.completion.chunk' per the OpenAI API contract.", example = "chat.completion.chunk")
    private String object;

    @Schema(description = "Unix timestamp (seconds) indicating when the chunk was generated by the model.", example = "1718700000")
    private long created;

    @Schema(description = "Identifier of the model that generated this chunk, e.g. 'gpt-4o' or a locally hosted model name.", example = "gpt-4o")
    private String model;

    @Schema(description = "List of streaming choices included in this chunk; typically contains exactly one element for non-branching completions.")
    private List<ChunkChoice> choices;

    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class ChunkChoice {

        @Schema(description = "Zero-based index of this choice within the choices array; typically 0 for single-completion requests.", example = "0")

        private int index;

        @Schema(description = "Incremental content delta for this chunk; accumulate all deltas across chunks to reconstruct the full message.")

        private Delta delta;

        @Schema(description = "Reason the model stopped generating tokens for this choice: 'stop' (natural end), 'length' (max tokens reached), 'tool_calls', or null if generation is still in progress.", example = "stop")

        @JsonProperty("finish_reason")
        private String finishReason;

    }

    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @ToString
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class Delta {

        @Schema(description = "Role of the message author; present only in the first chunk of a response, e.g. 'assistant'.", example = "assistant")

        private String role;

        @Schema(description = "Incremental text content for this chunk; concatenate all non-null content values across chunks to reconstruct the full assistant reply.", example = "Hello")

        private String content;

        @Schema(description = "Incremental chain-of-thought or reasoning text for this chunk, supported by reasoning-capable models (e.g. DeepSeek-R1); null for standard models.", example = "Let me think step by step...")

        @JsonProperty("reasoning_content")
        private String reasoningContent;

    }

}
