package io.github.pnoker.center.manager.mapper;

import io.github.pnoker.center.manager.entity.model.GroupDO;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 * 分组表 Mapper 接口
 * </p>
 *
 * @author Automatic Generated By Mybatis Plus
 * @since 2023-11-02
 */
public interface GroupMapper extends BaseMapper<GroupDO> {

}
