package io.github.pnoker.center.manager.mapper;

import io.github.pnoker.center.manager.entity.model.LabelBindDO;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 * 标签关联表 Mapper 接口
 * </p>
 *
 * @author Automatic Generated By Mybatis Plus
 * @since 2023-11-02
 */
public interface LabelBindMapper extends BaseMapper<LabelBindDO> {

}
