#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

dc3:
  driver:
    tenant: default
    name: OPC UA Driver
    code: OpcUaDriver
    type: DRIVER_CLIENT
    remark: @project.description@
    schedule:
      # Read data regularly
      read:
        enable: true
        cron: '0/30 * * * * ?'
      custom:
        enable: true
        cron: '0/5 * * * * ?'
    health:
      device:
        enable: true
        cron: '0/15 * * * * ?'
        timeout: 45
        timeout-unit: SECONDS
    driver-attribute:
      - attribute-name: Host
        attribute-code: host
        attribute-type-flag: STRING
        default-value: localhost
        remark: OPC UA host
      - attribute-name: Port
        attribute-code: port
        attribute-type-flag: INT
        default-value: 18600
        remark: OPC UA port
      - attribute-name: Path
        attribute-code: path
        attribute-type-flag: STRING
        default-value: /
        remark: OPC UA endpoint path
    point-attribute:
      - attribute-name: Namespace
        attribute-code: namespace
        attribute-type-flag: INT
        default-value: 5
        remark: OPC UA namespace index
      - attribute-name: Tag
        attribute-code: tag
        attribute-type-flag: STRING
        default-value: TAG
        remark: OPC UA node tag name

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - ${NODE_ENV:dev}

logging:
  file:
    name: dc3/logs/driver/opc-ua/${spring.application.name}.log
