/*
 * Copyright 2016-present the IoT DC3 original author or authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package io.github.pnoker.common.controller;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.method.HandlerMethod;
import org.springframework.web.reactive.result.method.RequestMappingInfo;
import org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping;
import reactor.core.publisher.Mono;

import java.util.*;

/**
 * Auto-discovery endpoint for MCP tool definitions.
 * <p>
 * Every backend service (auth, manager, data, agentic) inherits this controller
 * via {@code dc3-common-web}. At startup, the Gateway's MCP server calls each
 * service's {@code GET /mcp_tools} endpoint to collect all available API tools.
 * <p>
 * Tools are generated by introspecting the service's own
 * {@link RequestMappingHandlerMapping} — so they are ALWAYS in sync with the
 * actual controllers. No hardcoding, no manual maintenance.
 * <p>
 * Internal endpoints (/mcp_tools itself, actuator, error handlers) are excluded.
 *
 * @author pnoker
 * @since 2026.6.0
 */
@Slf4j
@RestController
public class ServiceMcpToolsController {

    @Autowired(required = false)
    private RequestMappingHandlerMapping handlerMapping;

    /**
     * Returns all MCP tool definitions for this service.
     * Called by the Gateway at startup.
     */
    @GetMapping("/mcp_tools")
    public Mono<Map<String, Object>> getMcpTools() {
        if (handlerMapping == null) {
            return Mono.just(Map.of("tools", List.of(), "error", "HandlerMapping not available"));
        }

        List<Map<String, Object>> tools = new ArrayList<>();
        Map<RequestMappingInfo, HandlerMethod> handlerMethods = handlerMapping.getHandlerMethods();

        for (Map.Entry<RequestMappingInfo, HandlerMethod> entry : handlerMethods.entrySet()) {
            RequestMappingInfo info = entry.getKey();
            HandlerMethod method = entry.getValue();

            // Skip internal/actuator endpoints
            String className = method.getBeanType().getName();
            if (isInternal(className)) {
                continue;
            }

            // Extract path patterns
            Set<String> patterns = info.getPatternsCondition() != null
                    ? info.getPatternsCondition().getPatterns().stream()
                        .map(p -> p.getPatternString())
                        .collect(java.util.stream.Collectors.toSet())
                    : Set.of();
            if (patterns.isEmpty()) continue;

            // Extract HTTP methods
            Set<String> httpMethods = new LinkedHashSet<>();
            if (info.getMethodsCondition() != null) {
                info.getMethodsCondition().getMethods()
                        .forEach(m -> httpMethods.add(m.name()));
            }
            // If no explicit method, default to GET
            if (httpMethods.isEmpty()) {
                httpMethods.add("GET");
            }

            // Build tool name from class + method
            String toolName = buildToolName(className, method.getMethod().getName());

            // Build description from method metadata
            String description = buildDescription(className, method.getMethod().getName(), httpMethods);

            // Build input schema (basic)
            Map<String, Object> inputSchema = buildInputSchema(method);

            // Build tool definition for each path+method combination
            for (String path : patterns) {
                for (String httpMethod : httpMethods) {
                    // Skip /mcp_tools itself
                    if (path.equals("/mcp_tools")) continue;

                    // Build unique tool name when multiple paths/methods
                    String uniqueName = patterns.size() > 1 || httpMethods.size() > 1
                            ? toolName + "_" + path.replace("/", "_").replace("{", "").replace("}", "")
                            : toolName;

                    Map<String, Object> tool = new LinkedHashMap<>();
                    tool.put("name", uniqueName);
                    tool.put("description", description);
                    tool.put("httpMethod", httpMethod);
                    tool.put("apiPath", path);
                    tool.put("inputSchema", inputSchema);
                    tool.put("category", extractCategory(className));
                    tools.add(tool);
                }
            }
        }

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("tools", tools);
        result.put("count", tools.size());
        return Mono.just(result);
    }

    // ---- helpers ----

    private boolean isInternal(String className) {
        return className.startsWith("org.springframework.boot.actuate")
                || className.startsWith("org.springdoc")
                || className.contains("ServiceMcpToolsController")
                || className.contains("BasicErrorController")
                || className.startsWith("org.springframework.web");
    }

    private String buildToolName(String className, String methodName) {
        // io.github.pnoker.common.manager.controller.DeviceController → device
        String simpleName = className.contains(".")
                ? className.substring(className.lastIndexOf('.') + 1)
                : className;
        // DeviceController → device
        String domain = simpleName
                .replace("Controller", "")
                .replaceAll("([A-Z])", "_$1").toLowerCase()
                .replaceFirst("^_", "");
        // get_by_id, list, add, update, delete, ...
        return domain + "_" + methodName;
    }

    private String buildDescription(String className, String methodName, Set<String> httpMethods) {
        String simpleName = className.contains(".")
                ? className.substring(className.lastIndexOf('.') + 1)
                : className;
        String domain = simpleName.replace("Controller", "");
        String method = String.join(",", httpMethods);
        return domain + " - " + methodName + " (" + method + ")";
    }

    private String extractCategory(String className) {
        if (className.contains(".manager.")) return "manager";
        if (className.contains(".data.")) return "data";
        if (className.contains(".auth.")) return "auth";
        if (className.contains(".agentic.")) return "agentic";
        return "general";
    }

    private Map<String, Object> buildInputSchema(HandlerMethod method) {
        Map<String, Object> schema = new LinkedHashMap<>();
        schema.put("type", "object");

        Map<String, Object> properties = new LinkedHashMap<>();

        // Extract parameter info from the method
        java.lang.reflect.Method javaMethod = method.getMethod();
        java.lang.reflect.Parameter[] params = javaMethod.getParameters();

        List<String> required = new ArrayList<>();
        for (java.lang.reflect.Parameter param : params) {
            // Skip framework-injected types
            String paramType = param.getType().getName();
            if (paramType.startsWith("org.springframework")
                    || paramType.equals("reactor.core.publisher.Mono")
                    || paramType.equals("reactor.core.publisher.Flux")) {
                continue;
            }

            String paramName = param.getName();
            Map<String, Object> prop = new LinkedHashMap<>();
            prop.put("type", inferJsonType(param.getType()));
            prop.put("description", paramName);

            properties.put(paramName, prop);

            // Non-optional params (primitives are required)
            if (param.getType().isPrimitive()) {
                required.add(paramName);
            }
        }

        schema.put("properties", properties);
        if (!required.isEmpty()) {
            schema.put("required", required);
        }
        return schema;
    }

    private String inferJsonType(Class<?> javaType) {
        if (javaType == String.class) return "string";
        if (javaType == Long.class || javaType == long.class
                || javaType == Integer.class || javaType == int.class
                || javaType == Double.class || javaType == double.class
                || javaType == Float.class || javaType == float.class
                || javaType == Short.class || javaType == short.class) {
            return "number";
        }
        if (javaType == Boolean.class || javaType == boolean.class) return "boolean";
        if (javaType == List.class || javaType == Set.class || javaType == Collection.class) return "array";
        return "object";
    }
}
