#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Server configuration
server:
  port: ${DC3_AUTH_PORT:8300}

# Spring application configuration
spring:
  application:
    name: @project.artifactId@
  webflux:
    base-path: /auth
  # gRPC server configuration
  grpc:
    server:
      port: ${DC3_AUTH_GRPC_PORT:9300}
  # Active profile configuration, defaults to 'dev' if NODE_ENV is not set
  profiles:
    active:
      - ${NODE_ENV:dev}

# DC3 platform configuration
dc3:
  facade:
    mode: local

# Logging configuration
logging:
  file:
    name: dc3/logs/center/auth/${spring.application.name}.log
