#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

## HTTP listener and embedded Web server settings.
management.tcp.port = 15672
management.load_definitions = /etc/rabbitmq/definitions.json

## Prometheus metrics listener.
prometheus.tcp.port = 15692

## TCP listener settings.
listeners.tcp.default = 5672

## TLS listener settings
listeners.ssl.default = 5671

## On first start RabbitMQ will create a vhost and a user. These
## config items control what gets created.
## Relevant doc guide: https://rabbitmq.com/access-control.html
##
default_vhost = @RABBITMQ_DEFAULT_VHOST@
default_user = @RABBITMQ_DEFAULT_USER@
default_pass = @RABBITMQ_DEFAULT_PASS@
default_user_tags.administrator = true

## MQTT settings.
mqtt.listeners.tcp.default = 1883
mqtt.listeners.ssl.default = 8883
mqtt.allow_anonymous = false
mqtt.vhost = @RABBITMQ_DEFAULT_VHOST@
mqtt.exchange = @RABBITMQ_MQTT_EXCHANGE@

## STOMP settings.
stomp.listeners.tcp.default = 61613
stomp.default_vhost = @RABBITMQ_DEFAULT_VHOST@
stomp.default_user = @RABBITMQ_DEFAULT_USER@
stomp.default_pass = @RABBITMQ_DEFAULT_PASS@

## SSL settings.
ssl_options.password   = dc3-server
ssl_options.cacertfile = /data/rabbitmq/dc3/keys/ca.crt
ssl_options.certfile   = /data/rabbitmq/dc3/keys/server.crt
ssl_options.keyfile    = /data/rabbitmq/dc3/keys/server.key
ssl_options.verify     = verify_none
ssl_options.fail_if_no_peer_cert = false
ssl_options.versions.1 = tlsv1.3
ssl_options.versions.2 = tlsv1.2
