#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

dc3:
  driver:
    tenant: default
    name: MQTT Driver
    code: MqttDriver
    type: DRIVER_SERVER
    remark: @project.description@
    schedule:
      # Read data regularly
      read:
        enable: false
        cron: '0/30 * * * * ?'
      custom:
        enable: true
        cron: '0/5 * * * * ?'
    health:
      device:
        enable: true
        cron: '0/15 * * * * ?'
        timeout: 45
        timeout-unit: SECONDS
    point-attribute:
      - attribute-name: Command Topic
        attribute-code: commandTopic
        attribute-type-flag: STRING
        default-value: commandTopic
        remark: MQTT topic used by the point or device to receive downstream commands
      - attribute-name: Command QoS
        attribute-code: commandQos
        attribute-type-flag: INT
        default-value: 2
        remark: QoS level for the downstream command topic
    command-attribute:
      - attribute-name: Command Topic
        attribute-code: commandTopic
        attribute-type-flag: STRING
        default-value: commandTopic
        remark: MQTT topic used by the command to publish downstream payload
      - attribute-name: Command QoS
        attribute-code: commandQos
        attribute-type-flag: INT
        default-value: 2
        remark: QoS level for the command publish topic
      - attribute-name: Payload Template
        attribute-code: payloadTemplate
        attribute-type-flag: STRING
        default-value: '{}'
        remark: Payload template rendered with command params
    event-attribute:
      - attribute-name: Source Topic
        attribute-code: sourceTopic
        attribute-type-flag: STRING
        default-value: eventTopic
        remark: MQTT topic used to receive event payload
      - attribute-name: Event Code Path
        attribute-code: eventCodePath
        attribute-type-flag: STRING
        default-value: $.eventCode
        remark: JSON path used to resolve event code
      - attribute-name: Payload Path
        attribute-code: payloadPath
        attribute-type-flag: STRING
        default-value: $.payload
        remark: JSON path used to resolve event payload

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - ${NODE_ENV:dev}

logging:
  file:
    name: dc3/logs/driver/mqtt/${spring.application.name}.log
