/*
 * Copyright 2016-present the IoT DC3 original author or authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package api.common.manager;

import "api/common/page.proto";
import "api/common/entity.proto";
import "api/common/manager/manager_query.proto";

// Configuration options for code generation
option java_package = "io.github.pnoker.api.center.manager";
option java_outer_classname = "ManagerDeviceProto";
option objc_class_prefix = "Manager";
option java_multiple_files = true;

// Service interface defining RPC calls related to device management
service DeviceApi {
  // Canonical offset-based query. Page-number RPCs are retired for new clients.
  rpc List (GrpcOffsetDeviceQuery) returns (GrpcOffsetPageDeviceDTO);
  // Query device list by Profile ID
  rpc ListByProfileId (GrpcProfileQuery) returns (GrpcDeviceListDTO);
  // Query device list by Driver ID
  rpc ListByDriverId (GrpcDriverQuery) returns (GrpcDeviceListDTO);
  // Query single device information by Device ID
  rpc GetByDeviceId (GrpcDeviceQuery) returns (GrpcDeviceDTO);
  // Batch query device information by Device IDs
  rpc ListByDeviceIds (GrpcDeviceIdsQuery) returns (GrpcDeviceListDTO);
  // Resolve the active runtime owner used for fenced command routing.
  rpc GetActiveOwner (GrpcDeviceQuery) returns (GrpcDeviceOwnerDTO);
}

message GrpcOffsetDeviceQuery {
  PageRequest page = 1;
  int64 tenant_id = 2;
  string device_name = 3;
  string device_code = 4;
  optional int64 driver_id = 5;
  optional int64 profile_id = 6;
  optional int32 enable_flag = 7;
  optional int32 version = 8;
  optional int64 group_id = 9;
  optional int64 label_id = 10;
}

message GrpcOffsetPageDeviceDTO {
  OffsetPage page = 1;
  repeated GrpcDeviceDTO items = 2;
}


// Response wrapper for device list query
message GrpcDeviceListDTO {
  repeated GrpcDeviceDTO items = 1;
}

// Response wrapper for single device query
message GrpcDeviceOwnerDTO {
  int64 driver_id = 1;
  string owner_node = 2;
  int64 fencing_token = 3;
}
