/*
 * Copyright 2016-present the IoT DC3 original author or authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package api.common.manager;

import "api/common/page.proto";
import "api/common/entity.proto";
import "api/common/manager/manager_query.proto";

option java_package = "io.github.pnoker.api.center.manager";
option java_outer_classname = "ManagerProfileProto";
option objc_class_prefix = "Manager";
option java_multiple_files = true;

// Service interface defining RPC calls related to profile/template management
service ProfileApi {
  // Canonical offset-based query. Page-number RPCs are retired for new clients.
  rpc List (GrpcOffsetProfileQuery) returns (GrpcOffsetPageProfileDTO);
  // Query single profile/template information by Profile ID
  rpc GetByProfileId (GrpcProfileQuery) returns (GrpcProfileDTO);
  // Batch query profile/template information by Profile IDs
  rpc ListByProfileIds (GrpcProfileIdsQuery) returns (GrpcProfileListDTO);
  // Query profiles/templates bound to a Device ID
  rpc ListByDeviceId (GrpcDeviceQuery) returns (GrpcProfileListDTO);
}

// Canonical offset-based profile query.
message GrpcOffsetProfileQuery {
  PageRequest page = 1;
  int64 tenant_id = 2;
  string profile_name = 3;
  string profile_code = 4;
  optional int32 profile_share_flag = 5;
  optional int32 profile_type_flag = 6;
  optional int32 enable_flag = 7;
  optional int32 version = 8;
  optional int64 group_id = 9;
  optional int64 label_id = 10;
  optional int64 device_id = 11;
}

message GrpcOffsetPageProfileDTO {
  OffsetPage page = 1;
  repeated GrpcProfileDTO items = 2;
}


// Response wrapper for profile list query
message GrpcProfileListDTO {
  repeated GrpcProfileDTO items = 1;
}
