#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

driver:
  tenant: default
  name: 虚拟Tcp/Udp驱动
  code: ListeningVirtualDriver
  type: DRIVER_SERVER
  remark: @project.description@
  custom:
    tcp:
      port: ${TCP_PORT:6270}
    udp:
      port: ${UDP_PORT:6271}
  schedule:
    # 定时读数据
    read:
      enable: false
      cron: '0/30 * * * * ?'
    custom:
      enable: true
      cron: '0/5 * * * * ?'
  point-attribute:
    - attribute-name: 关键字
      attribute-code: key
      attribute-type-flag: STRING
      default-value: 62
      remark: 报文关键字
    - attribute-name: 起始字节
      attribute-code: start
      attribute-type-flag: INT
      default-value: 0
      remark: 起始字节, 包含该字节
    - attribute-name: 结束字节
      attribute-code: end
      attribute-type-flag: INT
      default-value: 8
      remark: 结束字节, 不包含该字节
    - attribute-name: 类型
      attribute-code: type
      attribute-type-flag: STRING
      default-value: string
      remark: 解析类型, short, int, long, float, double, boolean, string

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - ${NODE_ENV:dev}

logging:
  file:
    name: dc3/logs/driver/listening-virtual/${spring.application.name}.log