#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# # The following content will be overwritten by application-[dev|test|pre|pro].yml,
# that is: if the following properties are configured in application-[dev|test|pre|pro].yml,
# the property values configured in application.yml will be the main ones.
spring:
  transaction:
    rollback-on-commit-failure: true
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false

server:
  undertow:
    threads:
      io: 4
      worker: 64
    buffer-size: 16364
    accesslog:
      enabled: true
      prefix: ${spring.application.name}.
      pattern: '%h %l %u %t "%r" %s %b %Dms'

management:
  endpoints:
    web:
      exposure:
        include: prometheus