apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-mongo
  name: dc3-mongo
  namespace: dc3
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-mongo