apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-gateway
  name: dc3-gateway
  namespace: dc3
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-gateway