apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-resource
  name: dc3-resource
  namespace: dc3
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-resource