apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-rtmp
  namespace: dc3
  name: dc3-rtmp
spec:
  ports:
    - name: "8803"
      port: 8803
      targetPort: 8803
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-rtmp
