apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-opcua
  namespace: dc3
  name: dc3-opcua
spec:
  ports:
    - name: "8802"
      port: 8802
      targetPort: 8802
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-opcua