apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-register
  name: dc3-register
  namespace: dc3
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-register