#
# Copyright 2016-present the IoT DC3 original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### 1.生成 Salt
POST http://{{dc3-gateway}}/api/v3/auth/token/salt
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "tenant": "default",
  "name": "pnoker"
}


### 2.生成 Token
POST http://{{dc3-gateway}}/api/v3/auth/token/generate
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "tenant": "default",
  "name": "pnoker",
  "salt": "t0jhimcpug4rfcbn",
  "password": "885f2748de9d57605dcb578ad51ac16a"
}


### 3.校验 Token
POST http://{{dc3-gateway}}/api/v3/auth/token/check
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "tenant": "default",
  "name": "pnoker",
  "salt": "t0jhimcpug4rfcbn",
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJpby5naXRodWIucG5va2VyLmRjMy8xIiwic3ViIjoicG5va2VyIiwiaWF0IjoxNjk1MDIxODcxLCJleHAiOjE2OTUwNjUwNzF9.dAWQgVGhBbslZ-5FeqFww_uObEW0TMkyxmhpsGbFY9g"
}


### 4.注销 Token
POST http://{{dc3-gateway}}/api/v3/auth/token/cancel
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "tenant1": "default",
  "name": "pnoker"
}