name: Docker Image For Center Manager
on:
    push:
        tags:
            - 'dc3.release.*'
jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login Docker
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  platforms: linux/arm64,linux/amd64

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  file: dc3-center/dc3-center-manager/Dockerfile
                  context: '{{defaultContext}}:/'
                  platforms: linux/arm64,linux/amd64
                  tags: pnoker/dc3-center-manager:2025.2.4
