name: Docker Image For Gateway
on:
  push:
    tags:
      - "dc3.release.*"
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login Docker Default Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login Docker Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ vars.ALIYUN_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_TOKEN }}

      - name: Extract Version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/dc3.release.}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Extract Variables
        id: varsiables
        run: |
          echo "docker_registry_default=pnoker" >> $GITHUB_OUTPUT
          echo "docker_registry_aliyun=registry.cn-beijing.aliyuncs.com/dc3" >> $GITHUB_OUTPUT
          echo "service_version=2025.2.5" >> $GITHUB_OUTPUT
          echo "service_name_gateway=dc3-gateway" >> $GITHUB_OUTPUT
          echo "service_path_gateway=dc3-gateway" >> $GITHUB_OUTPUT

      - name: Build and Push For Gateway
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            PROFILE=pro
          context: "{{defaultContext}}:/"
          platforms: linux/arm64,linux/amd64
          file: ${{ steps.varsiables.outputs.service_path_gateway }}/Dockerfile
          cache-from: type=registry,ref=pnoker/${{ steps.varsiables.outputs.service_name_gateway }}:buildcache
          cache-to: type=registry,ref=pnoker/${{ steps.varsiables.outputs.service_name_gateway }}:buildcache,mode=max
          tags: |
            ${{ steps.varsiables.outputs.docker_registry_default }}/${{ steps.varsiables.outputs.service_name_gateway }}:latest
            ${{ steps.varsiables.outputs.docker_registry_default }}/${{ steps.varsiables.outputs.service_name_gateway }}:${{ steps.varsiables.outputs.service_version }}
            ${{ steps.varsiables.outputs.docker_registry_default }}/${{ steps.varsiables.outputs.service_name_gateway }}:${{ steps.version.outputs.version }}
            ${{ steps.varsiables.outputs.docker_registry_aliyun }}/${{ steps.varsiables.outputs.service_name_gateway }}:latest
            ${{ steps.varsiables.outputs.docker_registry_aliyun }}/${{ steps.varsiables.outputs.service_name_gateway }}:${{ steps.varsiables.outputs.service_version }}
            ${{ steps.varsiables.outputs.docker_registry_aliyun }}/${{ steps.varsiables.outputs.service_name_gateway }}:${{ steps.version.outputs.version }}
